patterns:
  - !ruby/regexp /[A-Z0-9]{20}/
  - !ruby/regexp /(\"|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)(\"|')?\s*(:|=>|=)\s*(\"|')?[A-Za-z0-9\/\+=]{40}(\"|')?/
  - !ruby/regexp /(\"|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?(\"|')?\s*(:|=>|=)\s*(\"|')?[0-9]{4}\-?[0-9]{4}\-?[0-9]{4}(\"|')?/
allowed:
  - !ruby/regexp /AKIAIOSFODNN7EXAMPLE/
  - !ruby/regexp /wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY/

  
  
